### Data Insights and Visualization 
On conclusion of the data wrangling process, a describe method was used
to summarize the database with the summarized outcome below.

### Introduction
WeRateDogs is a Twitter account that rates people's dogs with a humorous comment about the dog. The account was started in 2015 by college student Matt Nelson, and has received international media attention both for its popularity and for the attention drawn to social media copyright law when it was suspended by Twitter for breaking these aforementioned laws. 

WeRateDogs asks people to send photos of their dogs, then tweets selected photos rating and a humorous comment. Dogs are rated on a scale of one to ten, but are invariably given ratings in excess of the maximum, such as "13/10". Popular posts are re-posted on Instagram and Facebook. In 2017, Nelson started a spin-off Twitter account, Thoughts of Dog. <a href="https://en.wikipedia.org/wiki/WeRateDogs">Click to find more information on wikipedia</a>

<table>
<thead>
<tr class="header">
<th></th>
<th><strong>tweet_id</strong></th>
<th><blockquote>
<p><strong>rating</strong><br />
<strong>numerator</strong></p>
</blockquote></th>
<th><blockquote>
<p><strong>rating</strong><br />
<strong>denominator</strong></p>
</blockquote></th>
<th><blockquote>
<p><strong>favourite count</strong></p>
</blockquote></th>
<th><blockquote>
<p><strong>retweet count</strong></p>
</blockquote></th>
<th><strong>img_num</strong></th>
<th><blockquote>
<p><strong>p1_conf</strong></p>
</blockquote></th>
<th><blockquote>
<p><strong>p2_conf</strong></p>
</blockquote></th>
<th><blockquote>
<p><strong>p3_conf</strong></p>
</blockquote></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>count</strong></td>
<td><blockquote>
<p>1.99E+03</p>
</blockquote></td>
<td>1994</td>
<td>1994</td>
<td>1994</td>
<td>1994</td>
<td>1994</td>
<td>1994</td>
<td><blockquote>
<p>1.99E+03</p>
</blockquote></td>
<td><blockquote>
<p>1.99E+03</p>
</blockquote></td>
</tr>
<tr class="even">
<td><strong>mean</strong></td>
<td><blockquote>
<p>7.36E+17</p>
</blockquote></td>
<td><blockquote>
<p>12.215035</p>
</blockquote></td>
<td>10.51003</td>
<td>8895.7257</td>
<td>2766.753</td>
<td><blockquote>
<p>1.203109</p>
</blockquote></td>
<td><blockquote>
<p>0.593941</p>
</blockquote></td>
<td><blockquote>
<p>1.34E-01</p>
</blockquote></td>
<td><blockquote>
<p>6.02E-02</p>
</blockquote></td>
</tr>
<tr class="odd">
<td><blockquote>
<p><strong>std</strong></p>
</blockquote></td>
<td><blockquote>
<p>6.75E+16</p>
</blockquote></td>
<td><blockquote>
<p>41.463367</p>
</blockquote></td>
<td>7.261522</td>
<td>12213.193</td>
<td>4674.698</td>
<td><blockquote>
<p>0.560777</p>
</blockquote></td>
<td><blockquote>
<p>0.271954</p>
</blockquote></td>
<td><blockquote>
<p>1.01E-01</p>
</blockquote></td>
<td><blockquote>
<p>5.09E-02</p>
</blockquote></td>
</tr>
<tr class="even">
<td><blockquote>
<p><strong>min</strong></p>
</blockquote></td>
<td><blockquote>
<p>6.66E+17</p>
</blockquote></td>
<td>0</td>
<td>7</td>
<td>81</td>
<td>16</td>
<td>1</td>
<td><blockquote>
<p>0.044333</p>
</blockquote></td>
<td><blockquote>
<p>1.01E-08</p>
</blockquote></td>
<td><blockquote>
<p>1.74E-10</p>
</blockquote></td>
</tr>
<tr class="odd">
<td><strong>25%</strong></td>
<td><blockquote>
<p>6.76E+17</p>
</blockquote></td>
<td>10</td>
<td>10</td>
<td>1982</td>
<td>624.75</td>
<td>1</td>
<td><blockquote>
<p>0.362857</p>
</blockquote></td>
<td><blockquote>
<p>5.39E-02</p>
</blockquote></td>
<td><blockquote>
<p>1.62E-02</p>
</blockquote></td>
</tr>
<tr class="even">
<td><strong>50%</strong></td>
<td><blockquote>
<p>7.08E+17</p>
</blockquote></td>
<td>11</td>
<td>10</td>
<td>4136</td>
<td>1359.5</td>
<td>1</td>
<td><blockquote>
<p>0.587635</p>
</blockquote></td>
<td><blockquote>
<p>1.17E-01</p>
</blockquote></td>
<td><blockquote>
<p>4.95E-02</p>
</blockquote></td>
</tr>
<tr class="odd">
<td><strong>75%</strong></td>
<td><blockquote>
<p>7.88E+17</p>
</blockquote></td>
<td>12</td>
<td>10</td>
<td>11308</td>
<td>3220</td>
<td>1</td>
<td><blockquote>
<p>0.846285</p>
</blockquote></td>
<td><blockquote>
<p>1.95E-01</p>
</blockquote></td>
<td><blockquote>
<p>9.16E-02</p>
</blockquote></td>
</tr>
<tr class="even">
<td><strong>max</strong></td>
<td><blockquote>
<p>8.92E+17</p>
</blockquote></td>
<td>1776</td>
<td>170</td>
<td>132810</td>
<td>79515</td>
<td>4</td>
<td>1</td>
<td><blockquote>
<p>4.88E-01</p>
</blockquote></td>
<td><blockquote>
<p>2.73E-01</p>
</blockquote></td>
</tr>
</tbody>
</table>

The following conclusions was deduced:  
1. The most liked tweet has 132810 likes  
2. The most retweeted tweet has 79515 retweets  
The ratings numerator was divided by the denominator to obtain the
following results. Dogs ratings equivalent to 1.2 is the most common
with 454 dogs rated 1.2 can be deduced from the result

<table>
<thead>
<tr class="header">
<th><strong>S/N</strong></th>
<th><blockquote>
<p><strong>rating</strong></p>
</blockquote></th>
<th><strong>counts</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td><blockquote>
<p>1.2</p>
</blockquote></td>
<td>454</td>
</tr>
<tr class="even">
<td>2</td>
<td><blockquote>
<p>1</p>
</blockquote></td>
<td>413</td>
</tr>
<tr class="odd">
<td>3</td>
<td><blockquote>
<p>1.1</p>
</blockquote></td>
<td>403</td>
</tr>
<tr class="even">
<td>4</td>
<td><blockquote>
<p>1.3</p>
</blockquote></td>
<td>263</td>
</tr>
<tr class="odd">
<td>5</td>
<td><blockquote>
<p>0.9</p>
</blockquote></td>
<td>151</td>
</tr>
<tr class="even">
<td>6</td>
<td><blockquote>
<p>0.8</p>
</blockquote></td>
<td>98</td>
</tr>
<tr class="odd">
<td>7</td>
<td><blockquote>
<p>0.7</p>
</blockquote></td>
<td>53</td>
</tr>
<tr class="even">
<td>8</td>
<td><blockquote>
<p>1.4</p>
</blockquote></td>
<td>36</td>
</tr>
<tr class="odd">
<td>9</td>
<td><blockquote>
<p>0.6</p>
</blockquote></td>
<td>33</td>
</tr>
<tr class="even">
<td>10</td>
<td><blockquote>
<p>0.5</p>
</blockquote></td>
<td>31</td>
</tr>
<tr class="odd">
<td>11</td>
<td><blockquote>
<p>0.3</p>
</blockquote></td>
<td>19</td>
</tr>
<tr class="even">
<td>12</td>
<td><blockquote>
<p>0.4</p>
</blockquote></td>
<td>16</td>
</tr>
<tr class="odd">
<td>13</td>
<td><blockquote>
<p>0.2</p>
</blockquote></td>
<td>10</td>
</tr>
<tr class="even">
<td>14</td>
<td><blockquote>
<p>0.1</p>
</blockquote></td>
<td>5</td>
</tr>
<tr class="odd">
<td>15</td>
<td><blockquote>
<p>0</p>
</blockquote></td>
<td>2</td>
</tr>
<tr class="even">
<td>16</td>
<td><blockquote>
<p>177.6</p>
</blockquote></td>
<td>1</td>
</tr>
<tr class="odd">
<td>17</td>
<td><blockquote>
<p>1.126</p>
</blockquote></td>
<td>1</td>
</tr>
<tr class="even">
<td>18</td>
<td><blockquote>
<p>1.127</p>
</blockquote></td>
<td>1</td>
</tr>
<tr class="odd">
<td>19</td>
<td><blockquote>
<p>0.975</p>
</blockquote></td>
<td>1</td>
</tr>
<tr class="even">
<td>20</td>
<td>3.428571</td>
<td>1</td>
</tr>
<tr class="odd">
<td>21</td>
<td><blockquote>
<p>1.35</p>
</blockquote></td>
<td>1</td>
</tr>
<tr class="even">
<td>22</td>
<td><blockquote>
<p>42</p>
</blockquote></td>
<td>1</td>
</tr>
</tbody>
</table>





Finally, a visualization to show which source was used for the most
tweet in the dataset was made with the summary below. Twitter for iPhone
was the predominant tweet source

![title](image1.png)